version: '3.3'
services:
    pingvin-share:
        restart: "unless-stopped"
        ports:
            - '3000:3000'
        image: stonith404/pingvin-share
        environment:
            - APPWRITE_FUNCTION_API_KEY=${APPWRITE_FUNCTION_API_KEY}
            - PUBLIC_APPWRITE_HOST=${PUBLIC_APPWRITE_HOST}
            - PUBLIC_MAX_FILE_SIZE=${PUBLIC_MAX_FILE_SIZE}
            - PUBLIC_DISABLE_REGISTRATION=${PUBLIC_DISABLE_REGISTRATION}
            - PUBLIC_DISABLE_HOME_PAGE=${PUBLIC_DISABLE_HOME_PAGE}
            - PUBLIC_MAIL_SHARE_ENABLED=${PUBLIC_MAIL_SHARE_ENABLED}