version: '3.8'
services:
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - APP_URL=${APP_URL}
      - SHOW_HOME_PAGE=${SHOW_HOME_PAGE}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - "${PWD}/data/uploads:/opt/app/backend/uploads"
      - "${PWD}/data/pingvin-share.db:/opt/app/backend/prisma/pingvin-share.db"
