version: '3.8'
services:
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - APP_URL=${APP_URL}
      - SHOW_HOME_PAGE=${SHOW_HOME_PAGE}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION}
      - ALLOW_UNAUTHENTICATED_SHARES=${ALLOW_UNAUTHENTICATED_SHARES}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_RECIPIENTS_ENABLED=${EMAIL_RECIPIENTS_ENABLED}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    volumes:
      - "${PWD}/data:/opt/app/backend/data"
