version: '3.3'
services:
    pingvin-share:
        ports:
            - '3000:3000'
        image: stonith404/pingvin-share
        environment:
            - APPWRITE_FUNCTION_API_KEY=${APPWRITE_FUNCTION_API_KEY}
            - PUBLIC_APPWRITE_HOST=${PUBLIC_APPWRITE_HOST}
            - PUBLIC_MAX_FILE_SIZE=${PUBLIC_MAX_FILE_SIZE}