version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=pingvin-share
    ports:
      - '5432:5432'
    volumes:
      - pingvin-share-dev-db:/var/lib/postgresql/data
volumes:
  pingvin-share-dev-db: