name: "🌐 Language request"
description: "You want to contribute to a language that isn't on Crowdin yet?"
title: "🌐 Language request: "
labels: [language-request]
body:
  - type: input
    id: language-name-english
    attributes:
      label: "🌐 Language name (English)"
      placeholder: "Swiss German"
    validations:
      required: true
  - type: input
    id: language-name-native
    attributes:
      label: "🌐 Language name (native)"
      placeholder: "Schweizerdeutsch"
    validations:
      required: true
  - type: input
    id: language-code
    attributes:
      label: "🌐 Language code"
      placeholder: "de-CH"
    validations:
      required: true
